services:
  db:
    image: mysql:8.0
    container_name: mysql_fastapi
    environment:
      MYSQL_ROOT_PASSWORD: fastapi 
      MYSQL_DATABASE: fastapi   
      MYSQL_USER: fastapi             
      MYSQL_PASSWORD: fastapi  
    volumes:
      - db-vol:/var/lib/mysql   
    ports:
      - "3306:3306"              
  app:
    build:
        context: .
    container_name: api_fastapi
    volumes:
      - .:/code       
    ports:
      - "80:80"                
    depends_on:
      - db                      

volumes:
  # - app-vol:/app
  db-vol:
