services:
  # Serwer MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_fastapi
    environment:
      MYSQL_ROOT_PASSWORD: fastapi      # Hasło roota
      MYSQL_DATABASE: fastapi    # Nazwa domyślnej bazy danych
      MYSQL_USER: fastapi               # Nazwa użytkownika
      MYSQL_PASSWORD: fastapi       # Hasło użytkownika
    volumes:
      - db-data:/var/lib/mysql       # Dane przechowywane na wolumenie
    ports:
      - "3306:3306"                 # Mapowanie portu MySQL
  python:
    build:
        context: .
    volumes:
      - ./:/var/www/html          # Montowanie aplikacji z lokalnego folderu
      - "~/.ssh:/root/.ssh"
    ports:
      - "80:80"                 # Mapowanie portu MySQL
    depends_on:
      - mysql                        # Uruchamia się po MySQL


    ## Jak uruchomic alembic w konenerze!!!!!!!!!!!!!!
    # command: bash -c "cd /code && alembic upgrade head"

volumes:
  db-data:                           # Definicja wolumenu dla danych MySQL
