services:
  # Serwer MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_fastapi
    environment:
      MYSQL_ROOT_PASSWORD: fastapi      # Hasło roota
      MYSQL_DATABASE: fastapi    # Nazwa domyślnej bazy danych
      MYSQL_USER: fastapi               # Nazwa użytkownika
      MYSQL_PASSWORD: fastapi       # Hasło użytkownika
    volumes:
      - db-data:/var/lib/mysql       # Dane przechowywane na wolumenie
    ports:
      - "3306:3306"                 # Mapowanie portu MySQL

    # restart: always

  # Serwer Nginx
  # nginx:
  #   image: nginx:1.21-alpine         # Używamy lekkiej wersji Nginx z Alpine
  #   container_name: nginx
  #   volumes:
  #     - ./:/var/www/html          # Montowanie aplikacji z lokalnego folderu
  #     - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  # Montowanie pliku konfiguracyjnego Nginx
  #   ports:
  #     - "80:80"                      # Mapowanie portu HTTP
  #   # restart: always
  #   depends_on:
  #     - php                          # Uruchamia się po PHP
  #   networks:
  #     - jenkins_test
volumes:
  db-data:                           # Definicja wolumenu dla danych MySQL
